name: "CI"
on: [push, pull_request]
jobs:
  specs:
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ matrix.failure-allowed }}
    strategy:
      matrix:
        ruby-version: ['2.7.5', '3.0.3', '3.1.1']
        failure-allowed: [false]
        include:
        - ruby-version: 'head'
          failure-allowed: true
        - ruby-version: 'truffleruby'
          failure-allowed: true
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up Ruby
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run specs
        run: bundle exec rake
